name: catppuccin
description: Soothing pastel library for Dart.
version: 0.1.0
repository: https://github.com/aprilswind/catppuccin-dart

environment:
  sdk: ^3.0.7

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
