name: catppuccin
description: Soothing pastel library for Dart.
version: 0.2.2
repository: https://github.com/aprilswind/catppuccin-dart

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
